version: "3.8"
services:
  openfalcon:
    build:
      context: .
      dockerfile: Dockerfile-openfalcon
    environment:
      - MYSQL_PORT=root:123456@tcp\(127.0.0.1:3306\)
      - REDIS_PORT=127.0.0.1:6379
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    network_mode: host

  falcondashboard:
    build:
      context: .
      dockerfile: Dockerfile-falcondashboard
    external_links:
      - mysql
    environment:
      - API_ADDR=http://【本机ip】:8080/api/v1
      - PORTAL_DB_HOST=mysql
      - PORTAL_DB_PORT=3306
      - PORTAL_DB_USER=root
      - PORTAL_DB_PASS=123456
      - PORTAL_DB_NAME=falcon_portal
      - ALARM_DB_HOST=mysql
      - ALARM_DB_PORT=3306
      - ALARM_DB_USER=root
      - ALARM_DB_PASS=123456
      - ALARM_DB_NAME=alarms
    working_dir: /open-falcon/dashboard
    command: ["./control startfg"]
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    network_mode: bridge
